from langchain_community.vectorstores import FAISS

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.vectorstores import VectorStore
from langchain_core.vectorstores import VectorStoreRetriever
from langchain_core.documents import Document

class VectorDBManager:
    """Class that includes and creates a vector store."""

    def __init__(self, embeddings_model: HuggingFaceEmbeddings) -> None:
        self.embeddings = embeddings_model
        self.vector_store = None

    def create_from_documents(self, documents: list[Document]) -> VectorStore:
        """Create a FAISS VectorStore with the documents (chunks) sent by user.

        Args:
            documents (list[Document]): Documents (chunks) generated by RecursiveCharacterTextSplitter.split_documents()

        Returns:
            VectorStore: A vector store with the documents vectorized.
        """

        if not documents:
            return None
        
        self.vector_store = FAISS.from_documents(
            documents=documents,
            embedding=self.embeddings
        )
        return self.vector_store

    def add_documents(self, documents: list[Document]) -> None:
        """Add documents to an existing vector store. If the vector store doesn't exist, uses the method create_from_documents().

        Args:
            documents (list[Document]): Documents (chunks) generated by RecursiveCharacterTextSplitter.split_documents()
        """

        if not documents:
            return
        
        if self.vector_store:
            self.vector_store.add_documents(documents)
        else:
            self.create_from_documents(documents)

    def clear(self) -> None:
        """Clears the vector store."""
        self.vector_store = None

    def get_retriever(self) -> VectorStoreRetriever:
        """Get the retriever object of the vector store.

        Raises:
            ValueError: Raises if the vector store is not created.

        Returns:
            VectorStoreRetriever: Retriever object of the vector store.
        """        

        if not self.vector_store:
            raise ValueError('Vector store not created! Use the function VectorDBManager.create_from_documents()')
        return self.vector_store.as_retriever()

    def get_stats(self) -> dict:
        """Get stats about the vectorized database.

        Returns:
            dict: Vector Store stats.
        """

        if not self.vector_store:
            return {
                "chunks": 0,
                "total_chars": 0
            }

        # Chunks count
        num_chunks = self.vector_store.index.ntotal

        # Iterates over documents to text counting.
        total_chars = 0
        if hasattr(self.vector_store, 'docstore'):
            for doc_id, doc in self.vector_store.docstore._dict.items():
                total_chars += len(doc.page_content)

        return {
            "chunks": num_chunks,
            "total_chars": total_chars,
        }